favicon: /Snake.svg

# valine 
valine:
    # 评论
    enableComment: false 
    # 阅读量
    enableCounter: false
    # valine appID
    appID: 
    # valine appKey
    appKey: 
    placeholder: 请输入评论
    avatar: retro

# 是否开启“不蒜子”统计访问量
busuanzi: false

# 底部版权开始年份
siteStartYear: 2020